apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  selector:
    matchLabels:
      app: result
  replicas: 1
  template:
    metadata:
      name: result-rs
      labels:
        app: result
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/login-k8s-416220/voting-images/result
        name: result
        ports:
            - containerPort: 4000