apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/login-k8s-416220/voting-images/worker
          name: worker
  selector:
    matchLabels:
      app: worker
